name = "psicohub-backend"
compatibility_date = "2024-04-01"
compatibility_flags = [ "nodejs_compat" ]
# route = "api.psycohub.com"

[vars]
PROJECT_NAME = "psicohub"
FRONTEND_URL = "https://app.psycohub.com"
# FRONTEND_URL = "http://localhost:3000"
BACKEND_URL = "https://api.psycohub.com/v1"
# BACKEND_URL = "http://127.0.0.1:3001/v1"
COOKIE_DOMAIN = ".psycohub.com"
SESSION_DURATION = 7
DEFAULT_UPLOAD_SIZE = 2


# [env.development]
# route = "dev.api.psycohub.com"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"